# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import bridge_pb2 as bridge__pb2


class BridgeStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Run = channel.stream_stream(
        '/Bridge/Run',
        request_serializer=bridge__pb2.Item.SerializeToString,
        response_deserializer=bridge__pb2.Item.FromString,
        )


class BridgeServicer(object):

  def Run(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BridgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Run': grpc.stream_stream_rpc_method_handler(
          servicer.Run,
          request_deserializer=bridge__pb2.Item.FromString,
          response_serializer=bridge__pb2.Item.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Bridge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
