# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bridge_pb2 as bridge__pb2


class BridgeStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Init = channel.unary_unary(
        '/Bridge/Init',
        request_serializer=bridge__pb2.NullMessage.SerializeToString,
        response_deserializer=bridge__pb2.NullMessage.FromString,
        )
    self.Run = channel.stream_stream(
        '/Bridge/Run',
        request_serializer=bridge__pb2.Item.SerializeToString,
        response_deserializer=bridge__pb2.Item.FromString,
        )
    self.StoreScalarMetric = channel.unary_unary(
        '/Bridge/StoreScalarMetric',
        request_serializer=bridge__pb2.ScalarMetric.SerializeToString,
        response_deserializer=bridge__pb2.NullMessage.FromString,
        )


class BridgeServicer(object):

  def Init(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Run(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StoreScalarMetric(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BridgeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Init': grpc.unary_unary_rpc_method_handler(
          servicer.Init,
          request_deserializer=bridge__pb2.NullMessage.FromString,
          response_serializer=bridge__pb2.NullMessage.SerializeToString,
      ),
      'Run': grpc.stream_stream_rpc_method_handler(
          servicer.Run,
          request_deserializer=bridge__pb2.Item.FromString,
          response_serializer=bridge__pb2.Item.SerializeToString,
      ),
      'StoreScalarMetric': grpc.unary_unary_rpc_method_handler(
          servicer.StoreScalarMetric,
          request_deserializer=bridge__pb2.ScalarMetric.FromString,
          response_serializer=bridge__pb2.NullMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Bridge', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
