#!/usr/bin/env python

from __future__ import print_function

import argparse
import logging
import os.path
import sys

sys.path.append(os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        '..',
        '..'
    )
))

from environments.DeepMind_Lab.environment import run


def main():
    logging.basicConfig(
        format='%(asctime)s:%(levelname)s: %(message)s',
        level=logging.INFO
    )

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--rlx-server', type=str, default=None,
                        help='agent server address (host:port)')
    parser.add_argument('--length', type=int, default=8 * 10 ** 7,
                        help='Number of steps to run the agent')
    parser.add_argument('--width', type=int, default=84,
                        help='Horizontal size of the observations')
    parser.add_argument('--height', type=int, default=84,
                        help='Vertical size of the observations')
    parser.add_argument('--fps', type=int, default=20,
                        help='Number of frames per second')
    parser.add_argument('--runfiles-path', type=str, default=None,
                        help='Set the runfiles path to find DeepMind Lab data')
    parser.add_argument('--level-script', type=str, default='nav_maze_static_01',  # 'tests/demo_map'
                        help='The environment level script to load')
    parser.add_argument('--display', type=bool, default=False,
                        help='Activate display screen size')
    parser.add_argument('--frame-skip', type=int, default=4,
                        help='The number of frames to skip between successive observations')
    parser.add_argument('--action-size', type=str, default='medium',
                        help='You can choose between: full action size - 11 actions, medium - just \
                             6 actions for movement only and small - 3 actions for forward | left | right \
                             by: \'f\', \'full\', \'b\', \'big\', \'m\', \'medium\', \'s\', \'small\' respectively')

    args = parser.parse_args()
    if args.runfiles_path:
        deepmind_lab.set_runfiles_path(args.runfiles_path)

    run(
        rlx_server_url=args.rlx_server,
        level=args.level_script,
        width=args.width,
        height=args.height,
        display=args.display,
        fps=args.fps,
        frame_skip=args.frame_skip,
        action_size=args.action_size
    )


if __name__ == "__main__":
    main()
