#!/bin/bash

rlx_url=$(cat /run_env.rlx-server-url)
regime=$(cat /run_env.regime)
level=$(cat /run_env.level)
number='^[0-9]+$'

if [ -z "$regime" ]
then
    (cd /opt/lab/bazel-bin/random_agent.runfiles/org_deepmind_lab && ./random_agent --rlx-server $rlx_url:7001)
elif [ "$regime" == "display" ]
then
    if [ -z "$level" ]
    then
        (cd /opt/lab/bazel-bin/random_agent.runfiles/org_deepmind_lab && ./random_agent --rlx-server $rlx_url:7001 --display true)
    else
        (cd /opt/lab/bazel-bin/random_agent.runfiles/org_deepmind_lab && ./random_agent --rlx-server $rlx_url:7001 --display true --level-script "$level")
    fi
elif [ "$regime" -eq "$regime" ]
#elif [[ $regime =~ $number ]]
then
    for i in `seq 0 $((regime - 1))`;
    do
    if [ -z "$level" ]
    then
        (cd /opt/lab/bazel-bin/random_agent.runfiles/org_deepmind_lab && ./random_agent --rlx-server $rlx_url:7001 &)
    else
        (cd /opt/lab/bazel-bin/random_agent.runfiles/org_deepmind_lab && ./random_agent --rlx-server $rlx_url:7001 --level-script "$level" &)
    fi
    done
else
    echo "You've passed a wrong arguments... Please, relaunch the docker with the right one"
fi
