environment:
  run: python environment/training.py
  name: PongDeterministic-v4
  shape: [42, 42, 3]
  max_episodes: 100000
  infinite_run: false

algorithm:
  name: da3c                      # short name for algorithm to load

  input:
    shape: [42, 42, 3]                    # shape of input state
    history: 4                    # number of consecutive states to stack
    use_convolutions: true       # set to true to process input by convolution layers

  output:
    continuous: false              # set to true to switch to continuous action space
    action_size: 6                # action size for the given environment
    action_high: []
    action_low: []
    scale: 1.0                    # multiplier to scale continuous output

  hidden_sizes: [256]          # list of dense layers sizes, for ex. [128, 64]
  batch_size: 5                   # maximum batch size, which need to accumulate for one update

  use_icm: false                  # to use ICM, set to the True
  use_lstm: false                 # to use LSTM instead of FF, set to the True
  max_global_step: 100000000.0     # amount of maximum global steps to pass through the training

  entropy_beta: 0.01              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  use_gae: false                  # switcher for generalized advantage estimation
  gae_lambda: 1.0                 # lambda for generalized advantage estimation

  initial_learning_rate: 7e-4    # initial learning rate, which can be anneal by some procedure
  gradients_norm_clipping: 40.0  # gradients clipping by global norm, if false then it is ignored
  optimizer: Adam                 # name of optimizer to use within training

relaax-parameter-server:
  --bind: localhost:7000
  --metrics-dir: logs/da3c/metrics
  --checkpoint-dir: logs/da3c/checkpoints
  --log-level: INFO

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: INFO