algorithm:
  name: dppo

  input:
    shape: [0]
    history: 0
    use_convolutions: false

  output:
    continuous: false
    action_size: 4

  hidden_sizes: [10]

  batch_size: 5

  clip_e: 0.2
  learning_rate: 0.001

  combine_gradient: dc
  num_gradients: 4
  dc_lambda: 0.05

