---
# generic Policy Gradient configuration

algorithm:
  name: policy_gradient

  input:
    shape: [0]
    history: 1
    use_convolutions: false

  output:
    continuous: false
    action_size: 4

  hidden_sizes: [10]
  batch_size: 10
  learning_rate: 0.01
  GAMMA: 0.97 # rewards discount factor
