#!/usr/bin/env python

from __future__ import print_function

import argparse
import logging
import os.path
import sys

sys.path.append(os.path.normpath(
    os.path.join(
        os.path.dirname(__file__),
        '..',
        '..'
    )
))

from environments.OpenAI_Gym.environment import run


def main():
    logging.basicConfig(
        format='%(asctime)s:%(levelname)s: %(message)s',
        level=logging.INFO
    )

    parser = argparse.ArgumentParser()
    parser.add_argument('--rlx-server', type=str, default=None, help='RLX server address (host:port)')
    parser.add_argument('--env', type=str, help='Name of the gym\'s environment')
    parser.add_argument('--seed', type=int, default=None, help='Seed for random generator')
    parser.add_argument('--limit', type=int, default=None, help='Steps limit for the episode')
    args = parser.parse_args()

    run(
        rlx_server_url=args.rlx_server,
        env=args.env,
        seed=args.seed,
        limit=args.limit
    )


if __name__ == "__main__":
    main()
