#!/usr/bin/env python

from __future__ import print_function

import os.path
import sys

sys.path.append(os.path.normpath(os.path.join(
        os.path.dirname(__file__), '..', '..')))

from environments.OpenAI_Gym.environment import run


if __name__ == "__main__":
    run()
