#!/usr/bin/env python

from __future__ import print_function

import argparse
import logging
import os.path
import sys

import environment


if __name__ == "__main__":
    logging.basicConfig(
        format='%(asctime)s:%(levelname)s: %(message)s',
        level=logging.INFO
    )
    environment.run()
