---

environment:
  run: python environment/training.py
  steps: 3000
  max_episodes: 1
  infinite_run: False

relaax-metrics-server:
  enable_unknown_metrics: False
  metrics:
    episode_reward: true
    server_latency: true
    action: true
    mu: true
    sigma2: true
    critic: true

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: logs/checkpoints
  --log-level: INFO

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: INFO

algorithm:
  name: policy_gradient

  input:
    shape: [0]
    history: 1
    use_convolutions: false

  output:
    continuous: false
    action_size: 4

  hidden_sizes: [10]
  batch_size: 10
  learning_rate: 0.01
  GAMMA: 0.97 # rewards discount factor
