---

environment:
  run: python environment/training.py
  name: CartPole-v0
  shape: [4]                      # size of the input vector
  max_episodes: 1000
  infinite_run: False

relaax-metrics-server:
  enable_unknown_metrics: False
  metrics:
    episode_reward: true
    server_latency: true
    action: true
    mu: true
    sigma2: true
    critic: true

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO

relaax-parameter-server:
  bind: localhost:7000
  checkpoint-dir: logs/checkpoints
  log-level: INFO

relaax-rlx-server:
  bind: localhost:7001
  log-level: INFO

version: 1.1.0
algorithm:
  name: da3c

  input:
    shape: [4]                    # state: size of the input vector
    history: 1                    # number of consecutive states to stuck to represent an input
    use_convolutions: false       # set to True to use convolutions to process the input,
                                  # it uses the set of convolutions from universe architecture by default
  output:
    continuous: false             # set to True to handle with continuous action type
    action_size: 2                # action size for the given environment

  batch_size: 5                   # experience size for one update

  use_lstm: false                 # to use LSTM instead of FF, set to the True
  max_global_step: 4e5            # amount of maximum global steps to pass through the training

  rewards_gamma: 0.99             # rewards discount factor

  initial_learning_rate: 1e-2     # initial learning rate to start the training
  use_linear_schedule: True       # set to True to use linear learning rate annealing wrt max_global_step

  optimizer: RMSProp              # type of optimizer to use: Adam | RMSProp
  RMSProp:
    decay: 0.99
    epsilon: 0.1
