---
# There are sample for OpenAI Gym CartPole environment

environment:
  run: python environment/training.py
  name: CartPole-v0
  shape: [4]                      # size of the input vector
  max_episodes: 1000
  infinite_run: False

relaax-metrics-server:
  enable_unknown_metrics: false
  metrics:
    episode_reward: true
    server_latency: true
    action: true
    critic: true

  bind: localhost:7002
  metrics_dir: logs/metrics
  log_metrics_to_console: false
  log_level: INFO

relaax-parameter-server:
  bind: localhost:7000
  checkpoint-dir: logs/checkpoints
  log-level: INFO

relaax-rlx-server:
  bind: localhost:7001
  log-level: INFO

version: 1.1.0
algorithm:
  name: trpo
  subtype: trpo-d2

  input:
    shape: [4]                    # state: size of the input vector
    history: 1                    # number of consecutive states to stuck to represent an input
    use_convolutions: false       # set to True to use convolutions to process the input

  output:
    continuous: false             # set to True to handle with continuous action type
    action_size: 2                # action size for the given environment

  hidden_sizes: [24, 24]          # list of num_units for hidden layers
  activation: tanh                # activation for the set of layers defined in hidden_sizes

  use_filter: false               # set to True to use mean/std running filter for input
  async: false                    # set to True to collect experience without blocking the updater

  PG_OPTIONS:
    timestep_limit: 200           # length in steps for one round in environment
    n_iter: 10000                 # number of updates to pass through the training (training length)
    timesteps_per_batch: 1000     # number of experience to collect before update
    rewards_gamma: 0.995          # rewards discount factor
    gae_lambda: 0.97              # lambda from generalized advantage estimation

  TRPO:
    cg_damping: 0.1               # multiple of the identity to Fisher matrix during CG
    max_kl: 0.01                  # KL divergence between old and new policy
